AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
      sam-app: Sample SAM Template for sam-app

Parameters:
  StageName:
    Type: String
    Default: dev

Globals:
  Function:
    Timeout: 30
  
Resources:
  HelloWorldApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub HelloWorldApi
      StageName: !Ref StageName

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloWorldFunction
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      AutoPublishAlias: live
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello-world
            Method: GET
            RestApiId: !Ref HelloWorldApi

  